### ISSUE TITLE
可以加入ef code first以及mongodb的使用栗子嘛？

### ISSUE THREAD

**Issue by Thyiad** [loogn/NetApiStarter#1]
rt

**Comment by loogn** [comment]
因为没有用过ef，我后面会配合自己写的orm(loogn.ormlite)来写数据访问的例子，不过不支持mongodb

**Comment by Thyiad** [comment]
好吧。
那关于.net core身份验证这一块（Authentication、Authorization），楼主可以写篇博文不，感觉好复杂，有点绕。

**Comment by loogn** [comment]
我感觉官方文档就够了
验证：
https://docs.microsoft.com/zh-cn/aspnet/core/security/authentication/?view=aspnetcore-3.1
授权：
https://docs.microsoft.com/zh-cn/aspnet/core/security/authorization/introduction?view=aspnetcore-3.1
