### ISSUE TITLE
startup configure

### ISSUE THREAD

**Issue by Thyiad** [loogn/NetApiStarter#2]
楼主，我看你的startup.cs的Configure函数有第3个参数：
`public void Configure(IApplicationBuilder app, IWebHostEnvironment env, IOptions<AppSettings> settings)`
调试也的确发现有值
这里是会把前面configure的AppSettings注入进去吗？
services.Configure<AppSettings>(Configuration);

**Comment by loogn** [comment]
是的

**Comment by Thyiad** [comment]
哦哦，我以为只在controller的参数中才会自动有值
